spring:
  application:
    name: bill-managment
  cloud:
    config:
      enabled: false

server:
  port: 6002

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
