spring:
  application:
    name: invoice-generator
  cloud:
    config:
      enabled: false

server:
  port: 6003

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
